import { Inter } from "next/font/google";
import "./globals.css";
import UIProviders from "@/Providers/UIProviders";
import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProviders>
          <Header />
          <main>{children}</main>
          <Footer />
        </UIProviders>
      </body>
    </html>
  );
}
